// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	certv1alpha1 "github.com/gardener/cert-management/pkg/apis/cert/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CertificateRevocationLister helps list CertificateRevocations.
// All objects returned here must be treated as read-only.
type CertificateRevocationLister interface {
	// List lists all CertificateRevocations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*certv1alpha1.CertificateRevocation, err error)
	// CertificateRevocations returns an object that can list and get CertificateRevocations.
	CertificateRevocations(namespace string) CertificateRevocationNamespaceLister
	CertificateRevocationListerExpansion
}

// certificateRevocationLister implements the CertificateRevocationLister interface.
type certificateRevocationLister struct {
	listers.ResourceIndexer[*certv1alpha1.CertificateRevocation]
}

// NewCertificateRevocationLister returns a new CertificateRevocationLister.
func NewCertificateRevocationLister(indexer cache.Indexer) CertificateRevocationLister {
	return &certificateRevocationLister{listers.New[*certv1alpha1.CertificateRevocation](indexer, certv1alpha1.Resource("certificaterevocation"))}
}

// CertificateRevocations returns an object that can list and get CertificateRevocations.
func (s *certificateRevocationLister) CertificateRevocations(namespace string) CertificateRevocationNamespaceLister {
	return certificateRevocationNamespaceLister{listers.NewNamespaced[*certv1alpha1.CertificateRevocation](s.ResourceIndexer, namespace)}
}

// CertificateRevocationNamespaceLister helps list and get CertificateRevocations.
// All objects returned here must be treated as read-only.
type CertificateRevocationNamespaceLister interface {
	// List lists all CertificateRevocations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*certv1alpha1.CertificateRevocation, err error)
	// Get retrieves the CertificateRevocation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*certv1alpha1.CertificateRevocation, error)
	CertificateRevocationNamespaceListerExpansion
}

// certificateRevocationNamespaceLister implements the CertificateRevocationNamespaceLister
// interface.
type certificateRevocationNamespaceLister struct {
	listers.ResourceIndexer[*certv1alpha1.CertificateRevocation]
}
