// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CertificateListerExpansion allows custom methods to be added to
// CertificateLister.
type CertificateListerExpansion interface{}

// CertificateNamespaceListerExpansion allows custom methods to be added to
// CertificateNamespaceLister.
type CertificateNamespaceListerExpansion interface{}

// CertificateRevocationListerExpansion allows custom methods to be added to
// CertificateRevocationLister.
type CertificateRevocationListerExpansion interface{}

// CertificateRevocationNamespaceListerExpansion allows custom methods to be added to
// CertificateRevocationNamespaceLister.
type CertificateRevocationNamespaceListerExpansion interface{}

// IssuerListerExpansion allows custom methods to be added to
// IssuerLister.
type IssuerListerExpansion interface{}

// IssuerNamespaceListerExpansion allows custom methods to be added to
// IssuerNamespaceLister.
type IssuerNamespaceListerExpansion interface{}
