/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CertificateListerExpansion allows custom methods to be added to
// CertificateLister.
type CertificateListerExpansion interface{}

// CertificateNamespaceListerExpansion allows custom methods to be added to
// CertificateNamespaceLister.
type CertificateNamespaceListerExpansion interface{}

// IssuerListerExpansion allows custom methods to be added to
// IssuerLister.
type IssuerListerExpansion interface{}

// IssuerNamespaceListerExpansion allows custom methods to be added to
// IssuerNamespaceLister.
type IssuerNamespaceListerExpansion interface{}
