// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscertv1alpha1 "github.com/gardener/cert-management/pkg/apis/cert/v1alpha1"
	versioned "github.com/gardener/cert-management/pkg/client/cert/clientset/versioned"
	internalinterfaces "github.com/gardener/cert-management/pkg/client/cert/informers/externalversions/internalinterfaces"
	certv1alpha1 "github.com/gardener/cert-management/pkg/client/cert/listers/cert/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CertificateInformer provides access to a shared informer and lister for
// Certificates. Prefer using the type-safe variant (see [TypedCertificateInformer]).
type CertificateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() certv1alpha1.CertificateLister
}

// TypedCertificateInformer provides access to a shared informer and lister for
// Certificates, including the type-safe TypedInformer variant.
// It is a superset of CertificateInformer.
type TypedCertificateInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() CertificateIndexInformer
	Lister() certv1alpha1.CertificateLister
}

// CertificateIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type CertificateIndexInformer cache.TypedSharedIndexInformer[*apiscertv1alpha1.Certificate]

// CertificateHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Certificate.
type CertificateHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiscertv1alpha1.Certificate]

// CertificateDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Certificate.
type CertificateDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiscertv1alpha1.Certificate]

// CertificateFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Certificate.
type CertificateFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiscertv1alpha1.Certificate]

// CertificateIndexers is a specialization of [cache.TypedIndexers] for Certificate.
type CertificateIndexers = cache.TypedIndexers[*apiscertv1alpha1.Certificate]

// DeletedCertificate is a specialization of [cache.DeletedObject] for Certificate.
type DeletedCertificate = cache.DeletedObject[*apiscertv1alpha1.Certificate]

type certificateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCertificateInformer constructs a new informer for Certificate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCertificateInformer]).
func NewCertificateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewCertificateInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedCertificateInformer constructs a new informer for Certificate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCertificateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers CertificateIndexers) CertificateIndexInformer {
	return NewTypedCertificateInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredCertificateInformer constructs a new informer for Certificate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredCertificateInformer]).
func NewFilteredCertificateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedCertificateInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredCertificateInformer constructs a new informer for Certificate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredCertificateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers CertificateIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) CertificateIndexInformer {
	return NewTypedCertificateInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewCertificateInformerWithOptions constructs a new informer for Certificate type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCertificateInformerWithOptions]).
func NewCertificateInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedCertificateInformerWithOptions(client, namespace, options)
}

// NewTypedCertificateInformerWithOptions constructs a new informer for Certificate type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCertificateInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) CertificateIndexInformer {
	gvr := schema.GroupVersionResource{Group: "cert.gardener.cloud", Version: "v1alpha1", Resource: "certificates"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiscertv1alpha1.Certificate](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CertV1alpha1().Certificates(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CertV1alpha1().Certificates(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CertV1alpha1().Certificates(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CertV1alpha1().Certificates(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiscertv1alpha1.Certificate{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *certificateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedCertificateInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *certificateInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *certificateInformer) TypedInformer() CertificateIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscertv1alpha1.Certificate](f.factory.InformerFor(&apiscertv1alpha1.Certificate{}, f.defaultInformer))
}

func (f *certificateInformer) Lister() certv1alpha1.CertificateLister {
	return certv1alpha1.NewCertificateLister(f.Informer().GetIndexer())
}

// ToTypedCertificateInformer converts an untyped informer into a TypedCertificateInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Certificate. If that is not the case, calling type-safe methods of the returned
// TypedCertificateInformer leads to runtime panics. A safer alternative is to pass
// around a TypedCertificateInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedCertificateInformer(informer CertificateInformer) TypedCertificateInformer {
	if informer, ok := informer.(TypedCertificateInformer); ok {
		return informer
	}
	return &certificateTypedInformerAdapter{informer}
}

type certificateTypedInformerAdapter struct {
	CertificateInformer
}

func (a *certificateTypedInformerAdapter) TypedInformer() CertificateIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscertv1alpha1.Certificate](a.Informer())
}

// ToCertificateIndexInformer converts an untyped informer into a CertificateIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Certificate. If that is not the case, calling type-safe methods of the returned
// CertificateIndexInformer leads to runtime panics. A safer alternative is to pass
// around a CertificateIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToCertificateIndexInformer(informer cache.SharedIndexInformer) CertificateIndexInformer {
	if informer, ok := informer.(CertificateIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiscertv1alpha1.Certificate](informer)
}
