// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscertv1alpha1 "github.com/gardener/cert-management/pkg/apis/cert/v1alpha1"
	versioned "github.com/gardener/cert-management/pkg/client/cert/clientset/versioned"
	internalinterfaces "github.com/gardener/cert-management/pkg/client/cert/informers/externalversions/internalinterfaces"
	certv1alpha1 "github.com/gardener/cert-management/pkg/client/cert/listers/cert/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IssuerInformer provides access to a shared informer and lister for
// Issuers. Prefer using the type-safe variant (see [TypedIssuerInformer]).
type IssuerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() certv1alpha1.IssuerLister
}

// TypedIssuerInformer provides access to a shared informer and lister for
// Issuers, including the type-safe TypedInformer variant.
// It is a superset of IssuerInformer.
type TypedIssuerInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() IssuerIndexInformer
	Lister() certv1alpha1.IssuerLister
}

// IssuerIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type IssuerIndexInformer cache.TypedSharedIndexInformer[*apiscertv1alpha1.Issuer]

// IssuerHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Issuer.
type IssuerHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiscertv1alpha1.Issuer]

// IssuerDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Issuer.
type IssuerDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiscertv1alpha1.Issuer]

// IssuerFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Issuer.
type IssuerFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiscertv1alpha1.Issuer]

// IssuerIndexers is a specialization of [cache.TypedIndexers] for Issuer.
type IssuerIndexers = cache.TypedIndexers[*apiscertv1alpha1.Issuer]

// DeletedIssuer is a specialization of [cache.DeletedObject] for Issuer.
type DeletedIssuer = cache.DeletedObject[*apiscertv1alpha1.Issuer]

type issuerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIssuerInformer constructs a new informer for Issuer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedIssuerInformer]).
func NewIssuerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewIssuerInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedIssuerInformer constructs a new informer for Issuer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedIssuerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers IssuerIndexers) IssuerIndexInformer {
	return NewTypedIssuerInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredIssuerInformer constructs a new informer for Issuer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredIssuerInformer]).
func NewFilteredIssuerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedIssuerInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredIssuerInformer constructs a new informer for Issuer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredIssuerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers IssuerIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) IssuerIndexInformer {
	return NewTypedIssuerInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewIssuerInformerWithOptions constructs a new informer for Issuer type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedIssuerInformerWithOptions]).
func NewIssuerInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedIssuerInformerWithOptions(client, namespace, options)
}

// NewTypedIssuerInformerWithOptions constructs a new informer for Issuer type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedIssuerInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) IssuerIndexInformer {
	gvr := schema.GroupVersionResource{Group: "cert.gardener.cloud", Version: "v1alpha1", Resource: "issuers"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiscertv1alpha1.Issuer](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CertV1alpha1().Issuers(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CertV1alpha1().Issuers(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CertV1alpha1().Issuers(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CertV1alpha1().Issuers(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiscertv1alpha1.Issuer{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *issuerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedIssuerInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *issuerInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *issuerInformer) TypedInformer() IssuerIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscertv1alpha1.Issuer](f.factory.InformerFor(&apiscertv1alpha1.Issuer{}, f.defaultInformer))
}

func (f *issuerInformer) Lister() certv1alpha1.IssuerLister {
	return certv1alpha1.NewIssuerLister(f.Informer().GetIndexer())
}

// ToTypedIssuerInformer converts an untyped informer into a TypedIssuerInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Issuer. If that is not the case, calling type-safe methods of the returned
// TypedIssuerInformer leads to runtime panics. A safer alternative is to pass
// around a TypedIssuerInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedIssuerInformer(informer IssuerInformer) TypedIssuerInformer {
	if informer, ok := informer.(TypedIssuerInformer); ok {
		return informer
	}
	return &issuerTypedInformerAdapter{informer}
}

type issuerTypedInformerAdapter struct {
	IssuerInformer
}

func (a *issuerTypedInformerAdapter) TypedInformer() IssuerIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscertv1alpha1.Issuer](a.Informer())
}

// ToIssuerIndexInformer converts an untyped informer into a IssuerIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Issuer. If that is not the case, calling type-safe methods of the returned
// IssuerIndexInformer leads to runtime panics. A safer alternative is to pass
// around a IssuerIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToIssuerIndexInformer(informer cache.SharedIndexInformer) IssuerIndexInformer {
	if informer, ok := informer.(IssuerIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiscertv1alpha1.Issuer](informer)
}
