apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: cert-management
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: europe-docker.pkg.dev/gardener-project/public/cert-controller-manager
      docker:
        dockerfile: Dockerfile
        cacheFrom:
        - europe-docker.pkg.dev/gardener-project/public/cert-controller-manager
      hooks:
        after:
        - command: [ "sh", "-c", "hack/kind/skaffold-after-hock.sh" ]
manifests:
  rawYaml:
  - dev/manifests.yaml
deploy:
  kubectl: {}
