apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    high-availability-config.resources.gardener.cloud/type: controller
  name: cert-management-local
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: cert-management
      app.kubernetes.io/name: cert-management
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cert-management
        app.kubernetes.io/name: cert-management
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-runtime-apiserver: allowed
    spec:
      containers:
      - args:
        - --name=cert-controller-manager
        - --dns-namespace=default
        - --issuer.issuer-namespace=default
        - --server-port-http=443
        image: image:123
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: cert-management-local
        ports:
        - containerPort: 443
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      serviceAccountName: cert-management-local
status: {}
