#!/usr/bin/env sh
#
# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

VERSION_FILE="$(readlink -f "${SOURCE_PATH}/VERSION")"
VERSION="$(cat "${VERSION_FILE}")"
VERSIONTAG="${VERSION//-dev/-master}"

sed -i -e "s/newTag: .*/newTag: ${VERSIONTAG}/" "${SOURCE_PATH}/manifests/profiles/example/kustomization.yaml"
