#!/bin/bash
#
# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

rm -f ${GOPATH}/bin/*-gen

CURRENT_DIR=$(dirname $0)
PROJECT_ROOT="${CURRENT_DIR}"/..

source "$PROJECT_ROOT/build/settings.src"

rm -rf "$SCRIPT_ROOT/pkg/client/cert"

bash "${PROJECT_ROOT}"/vendor/k8s.io/code-generator/generate-groups.sh \
  "deepcopy,client,informer,lister" \
  $PKGPATH/pkg/client/$APINAME \
  $PKGPATH/pkg/apis \
  $APINAME:$APIVERSION \
  -h "${PROJECT_ROOT}/hack/LICENSE_BOILERPLATE.txt"
