//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&CertManagerConfiguration{}, func(obj interface{}) { SetObjectDefaults_CertManagerConfiguration(obj.(*CertManagerConfiguration)) })
	return nil
}

func SetObjectDefaults_CertManagerConfiguration(in *CertManagerConfiguration) {
	SetDefaults_CertManagerConfiguration(in)
	if in.CertManagerClientConnection != nil {
		SetDefaults_CertManagerClientConnection(in.CertManagerClientConnection)
	}
	SetDefaults_LeaderElectionConfiguration(&in.LeaderElection)
	SetDefaults_ServerConfiguration(&in.Server)
	SetDefaults_IssuerControllerConfig(&in.Controllers.Issuer)
}
