/*
 * SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package legobridge

import (
	"context"
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/go-acme/lego/v5/acme"
	"github.com/go-acme/lego/v5/lego"
	"github.com/go-acme/lego/v5/registration"
	"k8s.io/apimachinery/pkg/util/sets"

	"github.com/gardener/cert-management/pkg/shared"
	"github.com/gardener/cert-management/pkg/shared/metrics"
)

const (
	// KeyPrivateKey is the secret data key for the private key.
	KeyPrivateKey = "privateKey"
	// ObsoleteKeyEmail is the obsolete secret data key for the email. Although it is not used anymore, it is still allowed to specify it for backward compatibility.
	ObsoleteKeyEmail = "email"
	// KeyHmacKey is the secret data key for the MAC key for external account binding.
	KeyHmacKey = "hmacKey"
)

// RegistrationUser contains the data of a registration user.
type RegistrationUser struct {
	email           string
	caDirURL        string
	extendedAccount *acme.ExtendedAccount
	key             crypto.Signer

	eabKeyID   string
	eabHmacKey string
}

// GetEmail returns the email of the registration user.
func (u *RegistrationUser) GetEmail() string {
	return u.email
}

// GetRegistration returns the extended account.
func (u *RegistrationUser) GetRegistration() *acme.ExtendedAccount {
	return u.extendedAccount
}

// GetPrivateKey returns the private key of the registration user.
func (u *RegistrationUser) GetPrivateKey() crypto.Signer {
	return u.key
}

// EabHmacKey returns the MAC key if it is an external account binding
func (u *RegistrationUser) EabHmacKey() string {
	return u.eabHmacKey
}

// EabKeyID returns the key ID if it is an external account binding
func (u *RegistrationUser) EabKeyID() string {
	return u.eabKeyID
}

// CADirURL returns the URL of the ACME directory server
func (u *RegistrationUser) CADirURL() string {
	return u.caDirURL
}

// NewConfig creates a new lego config.
func (u *RegistrationUser) NewConfig(caDirURL string) *lego.Config {
	config := lego.NewConfig(u)
	config.CADirURL = caDirURL
	return config
}

// NewRegistrationUserFromEmail generates a private key and requests a new registration for the user.
func NewRegistrationUserFromEmail(issuerKey shared.IssuerKeyItf,
	email string, caDirURL string, secretData map[string][]byte, eabKeyID, eabHmacKey string,
) (*RegistrationUser, error) {
	privateKey, err := ExtractOrGeneratePrivateKey(secretData)
	if err != nil {
		return nil, err
	}

	return NewRegistrationUserFromEmailAndPrivateKey(issuerKey, email, caDirURL, privateKey, eabKeyID, eabHmacKey)
}

// ExtractOrGeneratePrivateKey extracts the private key from the secret or generates a new one.
func ExtractOrGeneratePrivateKey(secretData map[string][]byte) (crypto.Signer, error) {
	privkeyData, ok := secretData[KeyPrivateKey]
	var privateKey crypto.Signer
	var err error
	if ok {
		privateKey, err = BytesToPrivateKey(privkeyData)
	} else {
		privateKey, err = ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	}
	if err != nil {
		return nil, err
	}

	return privateKey, nil
}

// ValidatePrivateKeySecretDataKeys checks if the secret data contains only required and optional keys for a private key.
// Empty data is allowed, as the private key may be generated by auto-registration.
func ValidatePrivateKeySecretDataKeys(secretData map[string][]byte) error {
	allowedKeys := sets.New(KeyPrivateKey, ObsoleteKeyEmail)
	for key := range allowedKeys {
		value, ok := secretData[key]
		if ok && key == KeyPrivateKey {
			if _, err := BytesToPrivateKey(value); err != nil {
				return fmt.Errorf("value for key `%s` is invalid: %w", key, err)
			}
		}
	}

	var invalidKeys []string
	for k := range secretData {
		if _, ok := allowedKeys[k]; !ok {
			invalidKeys = append(invalidKeys, fmt.Sprintf("`%s`", k))
		}
	}
	if len(invalidKeys) > 0 {
		return fmt.Errorf("invalid secret data keys: %s", strings.Join(invalidKeys, ","))
	}

	return nil
}

// NewRegistrationUserFromEmailAndPrivateKey requests a user registration.
func NewRegistrationUserFromEmailAndPrivateKey(issuerKey shared.IssuerKeyItf,
	email string, caDirURL string, privateKey crypto.Signer, eabKid, eabHmacKey string,
) (*RegistrationUser, error) {
	user := &RegistrationUser{email: email, key: privateKey, caDirURL: caDirURL, eabKeyID: eabKid, eabHmacKey: eabHmacKey}
	config := user.NewConfig(caDirURL)

	ctx := context.Background()
	// A client facilitates communication with the CA server.
	client, err := lego.NewClient(config)
	if err != nil {
		return nil, err
	}
	var reg *acme.ExtendedAccount
	// New users will need to register
	if eabKid == "" {
		reg, err = client.Registration.Register(ctx, registration.RegisterOptions{TermsOfServiceAgreed: true})
	} else {
		reg, err = client.Registration.RegisterWithExternalAccountBinding(ctx, registration.RegisterEABOptions{
			TermsOfServiceAgreed: true,
			Kid:                  user.eabKeyID,
			HmacEncoded:          user.eabHmacKey,
		})
	}
	if err != nil {
		return user, err
	}
	user.extendedAccount = reg

	metrics.AddACMEAccountRegistration(issuerKey, reg.Location, email)

	return user, nil
}

// ToSecretData returns the registration user as a secret data map.
func (u *RegistrationUser) ToSecretData() (map[string][]byte, error) {
	privkey, err := privateKeyToBytes(u.key, false)
	if err != nil {
		return nil, fmt.Errorf("encoding private key failed: %w", err)
	}
	return map[string][]byte{KeyPrivateKey: privkey}, nil
}

// RawRegistration returns the registration as a byte array.
func (u *RegistrationUser) RawRegistration() ([]byte, error) {
	reg, err := json.Marshal(u.extendedAccount)
	if err != nil {
		return nil, fmt.Errorf("encoding registration failed: %w", err)
	}
	return reg, nil
}

// RegistrationConfig contains all parameters needed to restore a registration user.
type RegistrationConfig struct {
	// Required fields
	IssuerKey       shared.IssuerKeyItf
	Email           string
	CADirURL        string
	RegistrationRaw []byte
	SecretData      map[string][]byte

	// Optional EAB (External Account Binding) credentials
	EABKeyID   string
	EABHmacKey string

	AllowV4ToV5Migration bool // If true, allows automatic migration from v4 to v5 registration format
}

// RegistrationResult contains the restored user and migration metadata.
type RegistrationResult struct {
	User        *RegistrationUser
	UpdatedRaw  []byte // Always returned, may differ from input if migrated
	WasMigrated bool   // True if v4->v5 migration occurred
}

// RegistrationUserFactoryFunc is a function type for creating a registration user from email and private key.
type RegistrationUserFactoryFunc func(cfg *RegistrationConfig, privateKey crypto.Signer) (*RegistrationUser, error)

// RegistrationUserFromConfig restores a RegistrationUser using configuration struct.
// It supports automatic v4-to-v5 migration and signals when migration occurs via WasMigrated field.
func RegistrationUserFromConfig(cfg *RegistrationConfig) (*RegistrationResult, error) {
	if cfg == nil {
		return nil, fmt.Errorf("configuration cannot be nil")
	}
	// Validate required fields
	if cfg.IssuerKey == nil {
		return nil, fmt.Errorf("required field IssuerKey is missing")
	}
	if cfg.Email == "" {
		return nil, fmt.Errorf("required field Email is missing")
	}
	if cfg.CADirURL == "" {
		return nil, fmt.Errorf("required field CADirURL is missing")
	}

	return registrationUserFromConfigWithFactory(cfg, defaultRegistrationUserFactory)
}

func defaultRegistrationUserFactory(cfg *RegistrationConfig, privateKey crypto.Signer) (*RegistrationUser, error) {
	return NewRegistrationUserFromEmailAndPrivateKey(cfg.IssuerKey, cfg.Email, cfg.CADirURL, privateKey, cfg.EABKeyID, cfg.EABHmacKey)
}

func registrationUserFromConfigWithFactory(cfg *RegistrationConfig, factoryFunc RegistrationUserFactoryFunc) (*RegistrationResult, error) {
	privkeyBytes, ok := cfg.SecretData[KeyPrivateKey]
	if !ok {
		return nil, fmt.Errorf("`%s` data not found in secret", KeyPrivateKey)
	}
	privateKey, err := BytesToPrivateKey(privkeyBytes)
	if err != nil {
		return nil, err
	}

	reg := &acme.ExtendedAccount{}
	err = json.Unmarshal(cfg.RegistrationRaw, reg)
	if err != nil {
		return nil, fmt.Errorf("unmarshalling registration json failed: %w", err)
	}

	var updatedRaw []byte
	var user *RegistrationUser

	wasMigrated := false
	if reg.Location == "" {
		if !cfg.AllowV4ToV5Migration {
			return nil, fmt.Errorf("missing account URL in status (maybe outdated status)")
		}
		// invalid status, e.g. issuer created with acme-lego <= v4
		// get account info from ACME server (migration will be logged via WasMigrated flag)
		user, err = factoryFunc(cfg, privateKey)
		if err != nil {
			return nil, fmt.Errorf("migrating v4 registration to v5 failed: %w", err)
		}
		updatedRaw, err = user.RawRegistration()
		if err != nil {
			return nil, fmt.Errorf("registration marshalling failed: %w", err)
		}
		wasMigrated = true
	} else {
		metrics.AddACMEAccountRegistration(cfg.IssuerKey, reg.Location, cfg.Email)
		user = &RegistrationUser{
			email:           cfg.Email,
			extendedAccount: reg,
			caDirURL:        cfg.CADirURL,
			key:             privateKey,
			eabKeyID:        cfg.EABKeyID,
			eabHmacKey:      cfg.EABHmacKey,
		}
		updatedRaw = cfg.RegistrationRaw
	}

	return &RegistrationResult{
		User:        user,
		UpdatedRaw:  updatedRaw,
		WasMigrated: wasMigrated,
	}, nil
}
