// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/cert-management/pkg/client/cert/clientset/versioned/typed/cert/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCertV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCertV1alpha1) Certificates(namespace string) v1alpha1.CertificateInterface {
	return newFakeCertificates(c, namespace)
}

func (c *FakeCertV1alpha1) CertificateRevocations(namespace string) v1alpha1.CertificateRevocationInterface {
	return newFakeCertificateRevocations(c, namespace)
}

func (c *FakeCertV1alpha1) Issuers(namespace string) v1alpha1.IssuerInterface {
	return newFakeIssuers(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCertV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
