# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert.gardener.cloud/v1alpha1
kind: Issuer
metadata:
  name: issuer-prod
  namespace: default
  annotations:
  # class annotation only needed if cert-controller-manager is started with --cert-class=myclass
  #cert.gardener.cloud/class: myclass
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: some.user@mydomain.com
    autoRegistration: true
