apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: cert-selfsigned
  namespace: default
spec:
  commonName: ca1.mydomain.com
  isCA: true
  # optional: default is 90 days (2160h). Must be at least 2*30 days (1440h) with the default renewal window of 30 days.
  # duration: 1440h
  # optional defaults to RSA 2048
  # privateKey:
  #   algorithm: ECDSA
  #   size: 384
  # optional: list of email addresses to be included in the certificate as subject alternative names (SANs).
  # emailAddresses:
  #   - foo@example.com
  # optional: list of IP addresses to be included in the certificate as subject alternative names (SANs).
  # ipAddresses:
  #   - 1.1.1.1
  # optional: list of URIs to be included in the certificate as subject alternative names (SANs).
  # uris:
  #   - spiffe://example.com/foo
  # CSR can also be specified
  # csr: ...
  issuerRef:
    name: issuer-selfsigned
    namespace: default  # must be specified when issuer runs in shoot!
  # optional: secret where the certificate should be stored
  #secretRef:
  #  name: cert-selfsigned-foo
  #  namespace: default
