# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: cert-ca
  namespace: default
spec:
  commonName: cert1.mydomain.com
  dnsNames:
  - cert1.my-other-domain.com
  # if issuer is not specified, the default issuer is used
  issuerRef:
    name: issuer-ca
  # optionally specify secret to store certificate
  secretRef:
    name: cert-ca-secret
    namespace: default
