# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: cert-csr
  namespace: default
spec:
  csr: ...
  issuerRef:
    name: issuer-staging
  # optionally specify secret to store certificate
  secretRef:
    name: cert-csr-secret
    namespace: default