# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: cert-ca
  namespace: default
spec:
  commonName: cert1.mydomain.com
  dnsNames:
  - cert1.my-other-domain.com
  # optional: list of email addresses to be included in the certificate as subject alternative names (SANs).
  # emailAddresses:
  #   - foo@example.com
  # optional: list of IP addresses to be included in the certificate as subject alternative names (SANs).
  # ipAddresses:
  #   - 1.1.1.1
  # optional: list of URIs to be included in the certificate as subject alternative names (SANs).
  # uris:
  #   - spiffe://example.com/foo
  # if issuer is not specified, the default issuer is used
  issuerRef:
    name: issuer-ca
  # optionally specify secret to store certificate
  secretRef:
    name: cert-ca-secret
    namespace: default
