"name": "cert-management-local"
"namespace": "default"
"podLabels":
  "networking.gardener.cloud/to-dns": "allowed"
  "networking.gardener.cloud/to-runtime-apiserver": "allowed"
  "networking.gardener.cloud/to-public-networks": "allowed"
  "networking.gardener.cloud/to-private-networks": "allowed"
"image": "image:123"
"config":
  "httpServerPort": 443
