apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry

resources:
- namespace.yaml
- docker
- ghcr
- k8s
- europe-docker-pkg-dev
labels:
- includeSelectors: true
  pairs:
    app: registry
