/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/gardener/cert-management/pkg/apis/cert/v1alpha1"
	scheme "github.com/gardener/cert-management/pkg/client/cert/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CertificateRevocationsGetter has a method to return a CertificateRevocationInterface.
// A group's client should implement this interface.
type CertificateRevocationsGetter interface {
	CertificateRevocations(namespace string) CertificateRevocationInterface
}

// CertificateRevocationInterface has methods to work with CertificateRevocation resources.
type CertificateRevocationInterface interface {
	Create(ctx context.Context, certificateRevocation *v1alpha1.CertificateRevocation, opts v1.CreateOptions) (*v1alpha1.CertificateRevocation, error)
	Update(ctx context.Context, certificateRevocation *v1alpha1.CertificateRevocation, opts v1.UpdateOptions) (*v1alpha1.CertificateRevocation, error)
	UpdateStatus(ctx context.Context, certificateRevocation *v1alpha1.CertificateRevocation, opts v1.UpdateOptions) (*v1alpha1.CertificateRevocation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CertificateRevocation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CertificateRevocationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CertificateRevocation, err error)
	CertificateRevocationExpansion
}

// certificateRevocations implements CertificateRevocationInterface
type certificateRevocations struct {
	client rest.Interface
	ns     string
}

// newCertificateRevocations returns a CertificateRevocations
func newCertificateRevocations(c *CertV1alpha1Client, namespace string) *certificateRevocations {
	return &certificateRevocations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the certificateRevocation, and returns the corresponding certificateRevocation object, and an error if there is any.
func (c *certificateRevocations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CertificateRevocation, err error) {
	result = &v1alpha1.CertificateRevocation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("certificaterevocations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CertificateRevocations that match those selectors.
func (c *certificateRevocations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CertificateRevocationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CertificateRevocationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("certificaterevocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested certificateRevocations.
func (c *certificateRevocations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("certificaterevocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a certificateRevocation and creates it.  Returns the server's representation of the certificateRevocation, and an error, if there is any.
func (c *certificateRevocations) Create(ctx context.Context, certificateRevocation *v1alpha1.CertificateRevocation, opts v1.CreateOptions) (result *v1alpha1.CertificateRevocation, err error) {
	result = &v1alpha1.CertificateRevocation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("certificaterevocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certificateRevocation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a certificateRevocation and updates it. Returns the server's representation of the certificateRevocation, and an error, if there is any.
func (c *certificateRevocations) Update(ctx context.Context, certificateRevocation *v1alpha1.CertificateRevocation, opts v1.UpdateOptions) (result *v1alpha1.CertificateRevocation, err error) {
	result = &v1alpha1.CertificateRevocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("certificaterevocations").
		Name(certificateRevocation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certificateRevocation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *certificateRevocations) UpdateStatus(ctx context.Context, certificateRevocation *v1alpha1.CertificateRevocation, opts v1.UpdateOptions) (result *v1alpha1.CertificateRevocation, err error) {
	result = &v1alpha1.CertificateRevocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("certificaterevocations").
		Name(certificateRevocation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certificateRevocation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the certificateRevocation and deletes it. Returns an error if one occurs.
func (c *certificateRevocations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("certificaterevocations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *certificateRevocations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("certificaterevocations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched certificateRevocation.
func (c *certificateRevocations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CertificateRevocation, err error) {
	result = &v1alpha1.CertificateRevocation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("certificaterevocations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
