apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../base
namespace: certman-example
images:
  - name: europe-docker.pkg.dev/gardener-project/public/cert-controller-manager
    newTag: v0.13.1-master

patches:
  # example for adding command line flag
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-management
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --acme-deactivate-authorizations 
