apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../base
namespace: certman-example
images:
  - name: europe-docker.pkg.dev/gardener-project/public/cert-controller-manager
    newTag: v0.13.1-master

#commonLabels:
#  app.kubernetes.io/instance: my-instance-name

patches:
  # example for adding command line flag
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --acme-deactivate-authorizations 

  ## example: use different namespace for challenge DNSEntries
  #- target:
  #    group: apps
  #    version: v1
  #    kind: Deployment
  #    name: cert-controller-manager
  #  patch: |-
  #    - op: add
  #      path: /spec/template/spec/containers/0/args/-
  #      value: --dns-namespace=my-namespace
  #- target:
  #    kind: ClusterRole
  #    name: cert-controller-manager
  #  patch: |-
  #    - op: add
  #      path: /rules/-
  #      value:
  #        apiGroups:
  #          - dns.gardener.cloud
  #        resources:
  #          - dnsentries
  #        verbs:
  #          - get
  #          - list
  #          - update
  #          - watch
  #          - create
  #          - delete
